"""Initial migration

Revision ID: 52f39163d260
Revises: 
Create Date: 2026-07-11 11:41:46.202656
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '52f39163d260'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pivot_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.Enum('Fotos', 'Informações', 'Segurança', 'Direções', name='pivottypeenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('trail_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.Enum('a pé', 'bicicleta', 'moto', 'jipe', 'escalada', 'aquática', name='trailtypeenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('interesses_pessoais', sa.Text(), nullable=True),
    sa.Column('data_aniversario', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('trails',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('nome_social', sa.String(length=255), nullable=True),
    sa.Column('trail_type_id', sa.Uuid(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('dificuldade', sa.Enum('fácil', 'moderado', 'difícil', 'expert', name='dificuldadeenum'), nullable=False),
    sa.Column('distancia_km', sa.Float(), nullable=True),
    sa.Column('elevacao_m', sa.Float(), nullable=True),
    sa.Column('duracao_estimada', sa.String(length=50), nullable=True),
    sa.Column('condicoes', sa.Enum('aberta', 'fechada', 'perigo', 'em manutenção', name='condicoesenum'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trail_type_id'], ['trail_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pivots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trail_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pivot_type_id', sa.Uuid(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pivot_type_id'], ['pivot_types.id'], ),
    sa.ForeignKeyConstraint(['trail_id'], ['trails.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pivot_media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pivot_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['pivot_id'], ['pivots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pivot_media')
    op.drop_table('pivots')
    op.drop_table('trails')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('trail_types')
    op.drop_table('pivot_types')
    # ### end Alembic commands ###
